#!/usr/bin/env python3


import json
import sys
import os
import webbrowser

import boto3
import requests


try:
    service_name = sys.argv[1]
except IndexError:
    service_name = 'console'


federation_url = 'https://signin.aws.amazon.com/federation'

session = boto3.Session()
session_credentials = session.get_credentials()
region = session.region_name
if len(region) == 0:
    region = os.environ["AWS_REGION"]

if len(region) == 0:
    print(f"Error: region for current profile is unset, cannot navigate to {service_name}", file=sys.stderr)
    sys.exit(1)

destination_url = f'https://{region}.console.aws.amazon.com/{service_name}?region={region}'

credentials = {
    'sessionId': session_credentials.access_key,
    'sessionKey': session_credentials.secret_key,
    'sessionToken': session_credentials.token,
}

params = {
    'Action': 'getSigninToken',
    'SessionDuration': 43200,
    'Session': json.dumps(credentials),
}

response = requests.get(federation_url, params=params)


params = {
    'Action': 'login',
    'Destination': destination_url,
    'SigninToken': response.json()['SigninToken']
}

request = requests.Request('GET', federation_url, params=params).prepare()

print(f"Opening AWS service {service_name} in region {region} (url={destination_url}")
webbrowser.open(request.url)
